biocypher:
  offline: true
  debug: true
  schema_config_path: config/generated_schema_config_for_data.yaml

  head_ontology:
    url: config/ontologies/custom.ttl
    root_node: Ontology

  tail_ontologies:
    snomedct:
      url: config/ontologies/ontology_snomed_ct.owl
      head_join_node: snomedct
      tail_join_node: SNOMED CT Concept (SNOMED RT+CTV3)
    icd:
      url: config/ontologies/ontology_ICD10CM_patched.ttl
      head_join_node: ICD
      tail_join_node: Icdroot
    # TODO: Loinc is not yet supported -> wait for first release of https://loincsnomed.org

neo4j:
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
