# add your settings here (overriding the defaults)

biocypher:
  offline: true
  debug: false
  schema_config_path: config/generated_schema_config_for_data.yaml
  output_directory: data/build2neo

  head_ontology:
    url: config/ontologies/custom.ttl
    root_node: Ontology

  tail_ontologies:
    snomedct:
      url: config/ontologies/ontology_snomed_ct.owl
      head_join_node: snomedct
      tail_join_node: SNOMED CT Concept (SNOMED RT+CTV3)
    icd:
      url: config/ontologies/ontology_ICD10CM_patched.ttl
      head_join_node: ICD
      tail_join_node: Icdroot

neo4j:
  database_name: neo4j
  wipe: true
  delimiter: '\t'
  array_delimiter: '|'
  skip_duplicate_nodes: true
  skip_bad_relationships: true
  import_call_file_prefix: /data/build2neo
